- WiserTaskScheduler/WiserTaskScheduler/Core/Aggregates/BaseWorkerDependencyAggregate.cs
- WiserTaskScheduler/WiserTaskScheduler/Core/Interfaces/IBaseWorkerDependencyAggregate.cs
- WiserTaskScheduler/WiserTaskScheduler/Core/Interfaces/IErrorNotificationService.cs
- WiserTaskScheduler/WiserTaskScheduler/Core/Models/ConfigurationModel.cs
- WiserTaskScheduler/WiserTaskScheduler/Core/Models/WtsSettings.cs
- WiserTaskScheduler/WiserTaskScheduler/Core/Services/ConfigurationsService.cs
- WiserTaskScheduler/WiserTaskScheduler/Core/Services/ErrorNotificationService.cs
- WiserTaskScheduler/WiserTaskScheduler/Core/Workers/BaseWorker.cs
- WiserTaskScheduler/WiserTaskScheduler/Core/Workers/CleanupWorker.cs
- WiserTaskScheduler/WiserTaskScheduler/Core/Workers/ConfigurationsWorker.cs
- WiserTaskScheduler/WiserTaskScheduler/Core/Workers/MainWorker.cs
When emails are declared an email will be send to those people when the service fails.
https://app.asana.com/0/1200923549887805/1203553253619160
> Notify people by email when a service fails.

- WiserTaskScheduler/WiserTaskScheduler/Core/Factories/ActionsServiceFactory.cs
- WiserTaskScheduler/WiserTaskScheduler/Core/Models/ConfigurationModel.cs
- WiserTaskScheduler/WiserTaskScheduler/Core/Services/CleanupService.cs
- WiserTaskScheduler/WiserTaskScheduler/Core/Services/ConfigurationsService.cs
- WiserTaskScheduler/WiserTaskScheduler/Modules/CleanupWiserHistory/Interfaces/ICleanupWiserHistoryService.cs
- WiserTaskScheduler/WiserTaskScheduler/Modules/CleanupWiserHistory/Models/CleanupWiserHistoryModel.cs
- WiserTaskScheduler/WiserTaskScheduler/Modules/CleanupWiserHistory/Services/CleanupWiserHistoryService.cs
Add an action type to quickly configure the WTS to cleanup the history of specific entities.
https://app.asana.com/0/1201027711166952/1203532238643485
> Add action to cleanup Wiser History.

- WiserTaskScheduler/WiserTaskScheduler/Modules/Queries/Models/QueryModel.cs
- WiserTaskScheduler/WiserTaskScheduler/Modules/Queries/Services/QueriesService.cs
Allow queries to be performed within an action to use a transaction.
https://app.asana.com/0/7257459017111/1203588368810205
> Add support for transactions for queries.

- WiserTaskScheduler/WiserTaskScheduler/Modules/CleanupItems/Services/CleanupItemsService.cs
Check if the entity has been defined before attempting to get the information from the table.
https://app.asana.com/0/7257459017111/1202914728566827
> Add check for non-existing entities.

- WiserTaskScheduler/WiserTaskScheduler/Core/Services/LogService.cs
- WiserTaskScheduler/WiserTaskScheduler/Modules/Slack/modules/SlackSettings.cs
- WiserTaskScheduler/WiserTaskScheduler/Program.cs
https://app.asana.com/0/7257459017111/1201816475294296
> Refactor the implementation of Slack messaging.

- WiserTaskScheduler/WiserTaskScheduler/Core/Services/OAuthService.cs
- WiserTaskScheduler/WiserTaskScheduler/Modules/ServerMonitors/Services/ServerMonitorsService.cs
- WiserTaskScheduler/WiserTaskScheduler/Modules/Wiser/Interfaces/IWiserService.cs
- WiserTaskScheduler/WiserTaskScheduler/Modules/Wiser/Services/WiserService.cs
- WiserTaskScheduler/WiserTaskScheduler/Modules/WiserImports/Services/WiserImportsService.cs
No Asana ticket, just something I noticed into while testing.
> Small refactor of code to use async functions and to remove a Task.Run that didn't seem to do anything.

- WiserTaskScheduler/AutoUpdater/AutoUpdater.csproj
- WiserTaskScheduler/WiserTaskScheduler/Modules/Branches/Services/BranchQueueService.cs
- WiserTaskScheduler/WiserTaskScheduler/WiserTaskScheduler.csproj
Asana ticket: https://app.asana.com/0/1201027711166952/1204689722468874
> Copy stored procedures/functions to a branch when creating a branch

- WiserTaskScheduler/WiserTaskScheduler/Modules/ImportFiles/Enums/FileTypes.cs
- WiserTaskScheduler/WiserTaskScheduler/Modules/ImportFiles/Models/ImportFileModel.cs
- WiserTaskScheduler/WiserTaskScheduler/Modules/ImportFiles/Services/ImportFilesService.cs
Refactored file imports service to be able to support multiple file types and added XML import.
https://app.asana.com/0/7257459017111/1204050481956755
> Add option to import XML files.

- WiserTaskScheduler/AutoUpdater/Models/UpdateSettings.cs
- WiserTaskScheduler/AutoUpdater/Services/UpdateService.cs
MailSettings in updateSettings can already be provided through the GCL settings.
https://app.asana.com/0/7257459017111/1204954357441340
> Use GCL settings for the SMTP settings.

- WiserTaskScheduler/WiserTaskScheduler/Modules/Branches/Models/BranchQueueModel.cs
- WiserTaskScheduler/WiserTaskScheduler/Modules/Branches/Services/BranchQueueService.cs
- WiserTaskScheduler/WiserTaskScheduler/Modules/Wiser/Interfaces/ITaskAlertsService.cs
- WiserTaskScheduler/WiserTaskScheduler/Modules/Wiser/Services/TaskAlertsService.cs
- WiserTaskScheduler/WiserTaskScheduler/Modules/WiserImports/Models/WiserImportModel.cs
- WiserTaskScheduler/WiserTaskScheduler/Modules/WiserImports/Services/WiserImportsService.cs
The importsService already had functionality for that. So to prevent duplicate code, I created a new service to send notifications, so that we can call that from multiple places.
The notifications for deleting branches need to be added later, once the PR https://github.com/happy-geeks/wiser-task-scheduler/pull/96 is merged.
Asana ticket: https://app.asana.com/0/1201027711166952/1204683379940126
> Send notifications to Wiser user when creating/merging/deleting a branch is finished

- WiserTaskScheduler/AutoUpdater/Services/UpdateService.cs
In some cases it happened that during the deletion of a DLL the auto updater had no access to the file.
When the WTS has been stopped the updater waits for 1 minute before continuing to give the system time to release all resources.
Deletion is tried 5 times with a delay.
If it still fails an extra email notification has been added where this was missing to notify the developers.
https://app.asana.com/0/7257459017111/1205081825585426/f
> Minimize chance for failing to update WTS

- WiserTaskScheduler/WiserTaskScheduler/Core/Enums/OAuthGrantType.cs
- WiserTaskScheduler/WiserTaskScheduler/Core/Models/OAuth/OAuthModel.cs
- WiserTaskScheduler/WiserTaskScheduler/Core/Services/OAuthService.cs
Asana: https://app.asana.com/0/0/1205274501824055/f
Add GrantType to OAuth logic
Add option to send Cred. in a auth basic header or body
> Add GrantType to OAuth logic

- WiserTaskScheduler/AutoUpdater/Services/UpdateService.cs
Add using blocks for the ServiceController, possibly it keeps DLLs in use of the service it is controlling causing errors when deleting files.
Also extent wait time between deletion attempts to give more time.
https://app.asana.com/0/1205090868730163/1205081825585426
> Improvements to auto updater

- WiserTaskScheduler/WiserTaskScheduler/Modules/GenerateFiles/Services/GenerateFileService.cs
If none were provided the foreach loop tried to go over a null object.
> Validate if there are PDFs to merge

- WiserTaskScheduler/WiserTaskScheduler/Modules/Branches/Services/BranchQueueService.cs
When merging an item that was created in the branch, the item will be created in production. But in production it will, of course, get a new ID. For that we created the wiser_id_mappings table, to keep track of those IDs. But those IDs that were created in production, can already exist in the branch too. This caused problems when trying to change the IDs of these items in the branch to be the same as in production.
I discussed this with Mark and we came to the conclusion that it's best to leave the IDs as they are and keep the ID mappings table. The code already checks the ID mappings, so we didn't have to change much for that. To fix this in other ways, would mean many extra queries and checks, which would make merging branches a lot slower, so we decided to do it like this.
Asana …
> Branches - Fixed errors with merging

- WiserTaskScheduler/WiserTaskScheduler/Modules/Branches/Services/BranchQueueService.cs
https://app.asana.com/0/1201027711166952/1206054275314309
> Fix copying files on item links.

- WiserTaskScheduler/WiserTaskScheduler/Modules/DocumentStoreRead/Models/DocumentStoreReadModel.cs
- WiserTaskScheduler/WiserTaskScheduler/Modules/DocumentStoreRead/Services/DocumentStoreReadService.cs
https://app.asana.com/0/1200923549887805/1203802664624132
Add option to set publishedEnvironment after publish in document store read.
> Add option to set publishedEnvironment in document store read

- WiserTaskScheduler/WiserTaskScheduler/Modules/GenerateFiles/Services/GenerateFileService.cs
https://app.asana.com/0/1144661858028300/1206139426172841
> Null check on files from database to prevent object reference errors

- README.md
- WiserTaskScheduler/AutoUpdater/Models/UpdateSettings.cs
- WiserTaskScheduler/AutoUpdater/Services/UpdateService.cs
Get the latest version from an external site to support larger packages and retain multiple versions for quick access.
https://app.asana.com/0/7257459017111/1206152347113688
> Move version for updates out of Github

- WiserTaskScheduler/AutoUpdater/Services/UpdateService.cs
https://app.asana.com/0/7257459017111/1204954357441340
> Log errors if mailing for the auto updater fails.

- WiserTaskScheduler/WiserTaskScheduler/Core/Services/OAuthService.cs
Made some changes to how the expire time for OAuth tokens are saved and loaded:
* The culture for reading and writing the `DateTime` object is now always `InvariantCulture`.
* If parsing the saved `DateTime` value fails, then the `ExpireTime` is set to `DateTime.MinValue` so a new token will be retrieved.
[Asana ticket](https://app.asana.com/0/7257459017111/1205977256427366)
> OAuth token expire time changes

- WiserTaskScheduler/WiserTaskScheduler/Modules/ImportFiles/Models/ImportFileModel.cs
- WiserTaskScheduler/WiserTaskScheduler/Modules/ImportFiles/Models/XmlMapModel.cs
- WiserTaskScheduler/WiserTaskScheduler/Modules/ImportFiles/Services/ImportFilesService.cs
Import from directory, import XML files with mapping and move files after import.
https://app.asana.com/0/1205727761850957/1204776183435257
> Extended import functionality

- WiserTaskScheduler/WiserTaskScheduler/Core/Services/MainService.cs
https://app.asana.com/0/1205090868730163/1205990065054162
> Improve the stopping of configurations and add extra logging.

- WiserTaskScheduler/WiserTaskScheduler/Modules/ImportFiles/Services/ImportFilesService.cs
Allows for multiple rows to be imported from one XML file through the use of the `[j]` indexer in an XPath expression. If using this indexer, all XPath expressions must be identical up to the part where the `[j]` indexer is set.
[Asana ticket](https://app.asana.com/0/1200923549887805/1206503303814635)
> Added support to indexed XPath Expressions

- WiserTaskScheduler/AutoUpdater/AutoUpdater.csproj
- WiserTaskScheduler/WiserTaskScheduler/Modules/Branches/Services/BranchQueueService.cs
- WiserTaskScheduler/WiserTaskScheduler/WiserTaskScheduler.csproj
Fixed timeout errors and other errors that sometimes occurred when creating a branch.
Asana ticket: https://app.asana.com/0/1204297502076149/1206444007637932
> Improvements to creating branches

- WiserTaskScheduler/WiserTaskScheduler/Core/Workers/BaseWorker.cs
- WiserTaskScheduler/WiserTaskScheduler/Modules/Wiser/Services/WiserDashboardService.cs
MainService and CleanupService are now also logged to the "wts_services" table to be able to add status checks on them.
https://app.asana.com/0/1205090868730163/1206039386998862
> Log state of default services

- WiserTaskScheduler/WiserTaskScheduler/Modules/Body/Models/BodyPartModel.cs
- WiserTaskScheduler/WiserTaskScheduler/Modules/Body/Services/BodyService.cs
- WiserTaskScheduler/WiserTaskScheduler/Modules/GenerateFiles/Services/GenerateFileService.cs
With inner bodies multiple loops can be created. The `[j]` and `[k]` indexes can be used to loop over different type of information.
https://app.asana.com/0/1201394730777422/1204634247322646
> Add support with inner body to create more advanced bodies.

- WiserTaskScheduler/WiserTaskScheduler/Modules/Communications/Services/CommunicationsService.cs
https://app.asana.com/0/1144661858028300/1206139426172844
Depends on: https://github.com/happy-geeks/geeks-core-library/pull/524
> Save SMTPeter API message ID

- WiserTaskScheduler/WiserTaskScheduler/Core/Interfaces/IParentUpdateService.cs
- WiserTaskScheduler/WiserTaskScheduler/Core/Models/ParentsUpdate/ParentsUpdateServiceSettings.cs
- WiserTaskScheduler/WiserTaskScheduler/Core/Models/WtsSettings.cs
- WiserTaskScheduler/WiserTaskScheduler/Core/Services/ParentUpdateService.cs
- WiserTaskScheduler/WiserTaskScheduler/Core/Workers/UpdateParentsWorker.cs
- WiserTaskScheduler/WiserTaskScheduler/Program.cs
pr related to: https://github.com/happy-geeks/wiser/pull/527
> add parentsupdateservice to WTS

- WiserTaskScheduler/WiserTaskScheduler/Modules/WiserImports/Services/WiserImportsService.cs
Bugfix in default mail content for mail after import
> Bugfix in default mail content for mail after import

- WiserTaskScheduler/WiserTaskScheduler/Core/Services/ParentUpdateService.cs
related to https://github.com/happy-geeks/wiser/pull/527
> add support for multiple target tables in parent update service

- WiserTaskScheduler/AutoUpdater/Models/WtsModel.cs
- WiserTaskScheduler/AutoUpdater/Services/UpdateService.cs
Able to override allowed days per WTS.
https://app.asana.com/0/7257459017111/1205112645650180
> Only allow updates during workdays by default

- WiserTaskScheduler/WiserTaskScheduler/Core/Services/MainService.cs
Prevent the main service from crashing if one configuration fails to parse.
https://app.asana.com/0/1205090868730163/1206278598828798
> Handle errors when parsing configurations fails.

- WiserTaskScheduler/WiserTaskScheduler/Modules/Branches/Models/BranchMergeFileCacheModel.cs
- WiserTaskScheduler/WiserTaskScheduler/Modules/Branches/Models/BranchMergeItemCacheModel.cs
- WiserTaskScheduler/WiserTaskScheduler/Modules/Branches/Models/BranchMergeLinkCacheModel.cs
- WiserTaskScheduler/WiserTaskScheduler/Modules/Branches/Services/BranchQueueService.cs
* Added support for styled output.
* Added more caching to improve the performance of merging a branch.
* Added functionality to log the progress of a branch merge in the database, so you can kind of see how far we are.
Asana ticket: https://app.asana.com/0/1205090868730163/1203267823719414
> Branches improvements

- WiserTaskScheduler/WiserTaskScheduler/Core/Aggregates/BaseWorkerDependencyAggregate.cs
- WiserTaskScheduler/WiserTaskScheduler/Core/Models/ParentsUpdate/ParentUpdateDatabaseStringsModel.cs
- WiserTaskScheduler/WiserTaskScheduler/Core/Models/ParentsUpdate/ParentsUpdateServiceSettings.cs
- WiserTaskScheduler/WiserTaskScheduler/Core/Services/ParentUpdateService.cs
https://app.asana.com/0/1199894242406919/1206544323178367/f
> add additional databases support to parent update service

- WiserTaskScheduler/WiserTaskScheduler/Core/Services/ParentUpdateService.cs
It was pointed out to me that Truncate is scary,
because of this I changed it over to the much less scary DELETE FROM thus resvolving the issue
I ran it wiserdemo and intergamma to make sure no errors showed, also ran the queries in navicat as well
none
https://app.asana.com/0/7257459017111/1207193040742564/f
> remove truncate from parent update service

- WiserTaskScheduler/AutoUpdater/AutoUpdater.csproj
- WiserTaskScheduler/WiserTaskScheduler/Modules/Branches/Models/BranchQueueModel.cs
- WiserTaskScheduler/WiserTaskScheduler/Modules/Branches/Services/BranchQueueService.cs
- WiserTaskScheduler/WiserTaskScheduler/WiserTaskScheduler.csproj
The branches functionality of Wiser was originally only made to work if both the branch and the production database are on the same SQL server. This PR changes that so that it also works if they are on different servers.
Please describe how you tested your changes and how you confirmed this functionality is not a breaking change.
https://github.com/happy-geeks/wiser/pull/622
https://app.asana.com/0/1205090868730163/1206931088376427
> Branches for multiple database servers

- WiserTaskScheduler/WiserTaskScheduler/Modules/Branches/Services/BranchQueueService.cs
Fixed problem that links were sometimes not merged when they should be. This was caused by the fact that the ID of `wiser_itemlink` is not saved in `wiser_history`, but this code assumed that it was.
I have tested these changes by making a fork database of a backup just before the moment that the original problem occurred. I then verified that I could reproduce the problem before making any changes and then tested my changes to see if they fixed the problem, which they did, and not cause new probems, which they didn't.
https://github.com/happy-geeks/geeks-core-library/pull/605
https://app.asana.com/0/7257459017111/1207597501842581/1207646424960318/f
> Fixed problem that links were sometimes not merged when they should be

- WiserTaskScheduler/WiserTaskScheduler/Modules/Queries/Services/QueriesService.cs
Added try/catch to prevent interruptions of configuration when a variable cannot be found because an API call returned an error
Ran a configuration with an API call that produces a 404, the configuration now continues running after logging the warning, instead of crashing with an error.
n/a
n/a
> Added try/catch

- WiserTaskScheduler/WiserTaskScheduler/Modules/Queries/Services/QueriesService.cs
When having queries in your XML configuration, the connection string that you can enter in the XML was mandatory, for some reason. We usually already have a connection string in the app settings, which is almost always the same as the connection string we would set in the XML configuration.
In the app settings we already have the option to set SSH settings for the connection to the database. We can't do this in the XML configuration yet. If there is a connection string in the XML configuration, it will also override the SSH settings with `null`, so I could not test the WTS on a database that requires SSH. This change also solves that problem.
We still should probably add support for SSH settings in XML configurations at some point though.
By running the WTS …
> Made connection string in configuration XML optional

- WiserTaskScheduler/WiserTaskScheduler/Modules/Branches/Services/BranchQueueService.cs
Some changes to `wiser_itemdetail` tables, such as changes to `language_code` and `key`, were never merged. This PR adds functionality to properly merge these changes.
I tested this by making several test branches in the wiser demo database and doing lots of test merges there.
https://github.com/happy-geeks/geeks-core-library/pull/616
https://github.com/happy-geeks/geeks-core-library/pull/616
https://app.asana.com/0/1205090868730163/1207370849820110
> Merge item detail changes

- WiserTaskScheduler/WiserTaskScheduler/Core/Models/ConfigurationModel.cs
- WiserTaskScheduler/WiserTaskScheduler/Core/Services/LogService.cs
Fixed null reference exception that sometimes occurred in logging service, because logSettings was null.
By reproducing the same situation as when the error occurred and checking if the logging works properly without exceptions.
N/A
No asana ticket, found this problem while working on something else.
> Fixed NullReferenceException in logService

- WiserTaskScheduler/WiserTaskScheduler/Core/Services/MainService.cs
Only 1 OAuth configuration can be used, having more will cause issues/unwanted results. If more than 1 OAuth configuration is found it will prevent the new configurations to be loaded.
Tested by having 0, 1 and 2 OAuth configurations loaded from Wiser.
N/A
https://app.asana.com/0/7257459017111/1206271423618053
> Prevent more than 1 OAuth configuration to be in use

- WiserTaskScheduler/WiserTaskScheduler/Modules/Queries/Services/QueriesService.cs
Check if an array has been found before proceeding. If not it will throw a more helpful error to find the problem.
Tested by having a path that is correct, a path that is incorrect halfway and a path that is correct up until the array itself.
N/A
https://app.asana.com/0/7257459017111/1206601135346945
> Handle if no array has been found.

- WiserTaskScheduler/WiserTaskScheduler/Modules/GenerateFiles/Services/GenerateFileService.cs
Give a useful error when the array was not present.
Tested by having a correct and incorrect path.
N/A
https://app.asana.com/0/1205090868730163/1205885370050586
> Improve error handling generating multiple files

- WiserTaskScheduler/WiserTaskScheduler/Modules/Communications/Services/CommunicationsService.cs
Add the date of the last attempt of communications
The column for when the last attempt was made wasn't being set by the WTS.
Tested by sending mails and check if the column is filled.
N/A
https://app.asana.com/0/1205090868730163/1207774443571247
> Add the date of the last attempt of communications

- WiserTaskScheduler/WiserTaskScheduler/Core/Interfaces/ILogService.cs
- WiserTaskScheduler/WiserTaskScheduler/Core/Services/CleanupService.cs
- WiserTaskScheduler/WiserTaskScheduler/Core/Services/LogService.cs
- WiserTaskScheduler/WiserTaskScheduler/Core/Services/MainService.cs
- WiserTaskScheduler/WiserTaskScheduler/Core/Services/ParentUpdateService.cs
- WiserTaskScheduler/WiserTaskScheduler/Core/Workers/BaseWorker.cs
- WiserTaskScheduler/WiserTaskScheduler/Modules/Wiser/Interfaces/IWiserDashboardService.cs
- WiserTaskScheduler/WiserTaskScheduler/Modules/Wiser/Services/WiserDashboardService.cs
Removed dependency on actual written logs to database. The new flow will always have the correct state no matter what logs are being logged due to settings.
Tested by checking if the state is still correctly determined.
N/A
https://app.asana.com/0/7257459017111/1206632390350850
> Refactor how the state of a service is decided

- WiserTaskScheduler/AutoUpdater/AutoUpdater.csproj
- WiserTaskScheduler/WiserTaskScheduler/Core/Enums/OAuthState.cs
- WiserTaskScheduler/WiserTaskScheduler/Core/Interfaces/IOAuthService.cs
- WiserTaskScheduler/WiserTaskScheduler/Core/Models/OAuth/OAuthModel.cs
- WiserTaskScheduler/WiserTaskScheduler/Core/Services/OAuthService.cs
- WiserTaskScheduler/WiserTaskScheduler/Modules/GenerateFiles/Services/GenerateFileService.cs
- WiserTaskScheduler/WiserTaskScheduler/Modules/HttpApis/Services/HttpApisService.cs
- WiserTaskScheduler/WiserTaskScheduler/WiserTaskScheduler.csproj
Some APIs we need to connect with, require this kind of authentication. This authentication requires a manual user login the first time. The WTS sends an email to the user with a link to login. That link will send them to the external system to login and then that system will send them back to a new page in the GCL (see related PR) so that we can store the authorization code that gets sent with that. Then the WTS can use that code for further authentication.
I also made a few other general code improvements for the OAUTH2 implementations of the WTS.
Note: Because I updated the GCL, I also had to make some changes to PDF generation that have nothing to do with this PR. I had to do this because otherwise I couldn't compile and test my changes. I wanted/needed the latest GCL for this.
Please …
> Added support for OAUTH2 authorization codes

- WiserTaskScheduler/WiserTaskScheduler/Core/Services/OAuthService.cs
Fixed problem that using OAUTH 2 refresh tokens did not work. There were multiple bugs with this:
* When the API returns an unauthorized result, we always removed the refresh token from the database and thus could no longer use it.
* We never set the grant type to refresh token, so we would also never try to use it.
* Some APIs require you to add a basic authorization header when using a refresh token, we did not do this.
By running the WTS locally after my access token was expired and then testing/checking if it uses the refresh token properly and authentication works again afterwards.
N/A
https://app.asana.com/0/29553867016121/1206714920405425
> Fixed problem that using OAUTH 2 refresh tokens did not work

- WiserTaskScheduler/WiserTaskScheduler/Modules/Branches/Services/BranchQueueService.cs
Fixed a few bugs in the merging of branches:
* Looking up a mapped ID would sometimes/often return an ID from a completely different table, which caused all kinds of problems and weird behavior.
* Fixed a very specific issue: If a value has been set in wiser_itemdetail first, then the key of that row gets changen, then someone adds the new key in production manually and also adds a row to wiser_id_mapping manually. In that case, the code would try to add a new mapping and then throw an error saying that a mapping already exists. I fixed this by checking if the ID is already known in the mapping and if so, then just using that ID to update the value in production.
* When a table has no rows in production and/or the branch, then we'd get an error about not being able to convert DBNull to an …
> Fixed a few bugs in the merging of branches

- WiserTaskScheduler/WiserTaskScheduler/Modules/Branches/Services/BranchQueueService.cs
Fixed several issues with branch merging:
* Fixed bug with ID mappings due to a new parameter that I added previously but forgot to actually use.
* Improved some code formatting and duplicate code.
* Objects that have been newly added in the branch database were not (correctly) copied to the production database, because I forgot to implement a parameter that I added.
* Merging styled output caused SQL exceptions due to invalid queries. Also refactored this code because the code was a bit strange and inefficient.
* Fixed problem that entity type settings and link type settings were retrieved from production database. This caused problems when a new entity or link has been added to production and not in the branch, especially if the new entity/link uses a table prefix.
* Fixed problems that …
> Branch merge improvements

- WiserTaskScheduler/WiserTaskScheduler/Core/Factories/ActionsServiceFactory.cs
- WiserTaskScheduler/WiserTaskScheduler/Core/Models/ConfigurationModel.cs
- WiserTaskScheduler/WiserTaskScheduler/Core/Services/ConfigurationsService.cs
- WiserTaskScheduler/WiserTaskScheduler/Modules/Scripts/Enums/Interpreters.cs
- WiserTaskScheduler/WiserTaskScheduler/Modules/Scripts/Interfaces/IScriptsService.cs
- WiserTaskScheduler/WiserTaskScheduler/Modules/Scripts/Models/ScriptModel.cs
- WiserTaskScheduler/WiserTaskScheduler/Modules/Scripts/Services/ScriptsService.cs
- WiserTaskScheduler/WiserTaskScheduler/WiserTaskScheduler.csproj
Adds a `<Script>` action that allows you to run JavaScript actions and manipulate a result set.
Tested it using a debug build with a test configuration and confirmed it all worked as intended.
Nope.
[Asana ticket](https://app.asana.com/1/5038780173035/project/29553867016121/task/1206403620159466)
> JavaScript interpreter

- WiserTaskScheduler/WiserTaskScheduler/Core/Services/CleanupService.cs
added code toc ealnup wiser_itemlink and deticated tables
I ran this in navicat but did not do any actual deletes, this code needs be checked by someone that knows wiser well, because i dont want to murder usefull data at costumers, the delete code is commented out so if this pull request goes by mistake it does not delete anything yet.
- [] I added new unit tests for my changes if applicable
nothing but us chickens
[Add a link to the Asana ticket. Note that **_ONLY_** the URL should be added, not the name of the ticket!](https://app.asana.com/1/5038780173035/project/1204371236183532/task/1208295860526632?focus=true)
> add wiser_itemlink clean up to the cleanup service
