happy-geeks/wiser-task-scheduler

WiserTaskScheduler/WiserTaskScheduler/Core/Aggregates/BaseWorkerDependencyAggregate.cs, WiserTaskScheduler/WiserTaskScheduler/Core/Interfaces/IBaseWorkerDependencyAggregate.cs, WiserTaskScheduler/WiserTaskScheduler/Core/Models/WtsSettings.cs, WiserTaskScheduler/WiserTaskScheduler/Core/Services/ConfigurationsService.cs, WiserTaskScheduler/WiserTaskScheduler/Core/Services/MainService.cs, WiserTaskScheduler/WiserTaskScheduler/Core/Workers/BaseWorker.cs, WiserTaskScheduler/WiserTaskScheduler/Program.cs, WiserTaskScheduler/WiserTaskScheduler/appsettings.json
It can become unclear what WTS has send an email if configuration names are used in multiple WTS services (such as "General").
A name can be provided to indicate which WTS needs attention.
https://app.asana.com/0/7257459017111/1203798696952557
=> Add name for WTS to use in error mails.

WiserTaskScheduler/WiserTaskScheduler/Core/Services/LogService.cs, WiserTaskScheduler/WiserTaskScheduler/Modules/Branches/Services/BranchQueueService.cs, WiserTaskScheduler/WiserTaskScheduler/Program.cs
Due to the MainService and CleanupService being on different threads starting both when running the WTS it was possible to have a race condition causing both threads to update columns resulting in an exception.
This check is now done before launching to prevent this.
https://app.asana.com/0/7257459017111/1202846788164815
=> Create and update tables before starting.

WiserTaskScheduler/WiserTaskScheduler/Core/Services/ErrorNotificationService.cs, WiserTaskScheduler/WiserTaskScheduler/Core/Services/LogService.cs
Both channels can be used to notify multiple people when things go wrong. During development the chance that happens increases and the other people that are involved don't need to be updated about that.
https://app.asana.com/0/7257459017111/1203890701686050
=> Only send the error notifications and Slack messages during production.

WiserTaskScheduler/WiserTaskScheduler/Core/Helpers/ReplacementHelper.cs, WiserTaskScheduler/WiserTaskScheduler/Core/Models/ParameterKeyModel.cs, WiserTaskScheduler/WiserTaskScheduler/Modules/Queries/Services/QueriesService.cs
Keys for replacement where added with just a question mark in front. This could cause problems, such as in a query string of an URL if the key matches the query paramater. This makes the replacement value with a random part.
https://app.asana.com/0/7257459017111/1203072017496981
=> Generate unique keys for replacements to prevent a key matching a value.

WiserTaskScheduler/WiserTaskScheduler/Core/Services/ConfigurationsService.cs
The `OnlyWithStatusCode` setting now supports the use of default values.
Asana: https://app.asana.com/0/5038781037429/1203762811573628
=> Allow default values for status code check

WiserTaskScheduler/WiserTaskScheduler/Core/Models/WtsSettings.cs, WiserTaskScheduler/WiserTaskScheduler/Core/Services/MainService.cs
Replace credentials in configuration files that are retrieved in the app settings secrets to prevent them from being visible within Wiser.
https://app.asana.com/0/7257459017111/1202245549978223
=> Add replacements during load for credentials.

WiserTaskScheduler/WiserTaskScheduler/Modules/Wiser/Services/WiserService.cs
https://app.asana.com/0/7257459017111/1204559100289197/f
When getting configurations from Wiser and Wiser is updating it will no longer log as a critical error but as information
=> Log information instead of Critical when Wiser is updating

WiserTaskScheduler/WiserTaskScheduler/Core/Workers/MainWorker.cs
The message was send when loading the configurations. But since this is a repeated process it kept sending the message.
https://app.asana.com/0/7257459017111/1204495804970023
=> Change the moment the WTS writes to Slack it has started.

WiserTaskScheduler/WiserTaskScheduler/Core/Models/Cleanup/CleanupServiceSettings.cs, WiserTaskScheduler/WiserTaskScheduler/Core/Services/CleanupService.cs
If the render times for templates and dynamic contents are logged they need to be cleaned to ensure the database is not filled with the logs. On high traffic websites this can go fast, therefor the days to store has its own setting.
https://app.asana.com/0/7257459017111/1204505225976506
=> Cleanup render times tables.

WiserTaskScheduler/AutoUpdater/AutoUpdater.csproj, WiserTaskScheduler/WiserTaskScheduler/Modules/Branches/Enums/CopyTypes.cs, WiserTaskScheduler/WiserTaskScheduler/Modules/Branches/Models/BranchQueueModel.cs, WiserTaskScheduler/WiserTaskScheduler/Modules/Branches/Models/CopyTableRuleModel.cs, WiserTaskScheduler/WiserTaskScheduler/Modules/Branches/Services/BranchQueueService.cs, WiserTaskScheduler/WiserTaskScheduler/WiserTaskScheduler.csproj
Add copy rules for tables when creating a branch to prevent custom tables to be copied.
Tables can be completely ignored or only the structure can be created if it needs to exist to be able to run the branch.
https://app.asana.com/0/1205090868730163/1205282683097489
=> Add table copy rules to exclude specific tables.

WiserTaskScheduler/WiserTaskScheduler/Modules/Branches/Services/BranchQueueService.cs
No Asana ticket, found this when trying to create a branch and immediately fixed it.
=> Fixed NullReferenceException that occurred when no CopyTableRules have been set

WiserTaskScheduler/WiserTaskScheduler/Modules/HttpApis/Models/HttpApiModel.cs, WiserTaskScheduler/WiserTaskScheduler/Modules/HttpApis/Services/HttpApisService.cs
asana: no asana point
this is needed to resolve a issue with some httpapi calls taking longer then the default 100 seconds
=> add timeout option to httpcalls

WiserTaskScheduler/WiserTaskScheduler/Core/Workers/BaseWorker.cs, WiserTaskScheduler/WiserTaskScheduler/Modules/Wiser/Interfaces/IWiserDashboardService.cs, WiserTaskScheduler/WiserTaskScheduler/Modules/Wiser/Services/WiserDashboardService.cs
Added try/catch blocks around wiser dashboard database calls and updated BaseWorker to handle failing calls to prevent WTS services from getting stuck.
[1206288367732036 - Configuratie crashed bij updaten service status bij fout](https://app.asana.com/0/1205090868730163/1206288367732036)
=> Added error handling around Wiser dashboard database calls

WiserTaskScheduler/AutoUpdater/Models/WtsModel.cs, WiserTaskScheduler/AutoUpdater/Services/UpdateService.cs
The auto updater checks at midnight if there is an update and then starts processing. For some projects this might be giving problem with nightly activities. This allows people to delay the actual update till a more favorable time.
https://app.asana.com/0/1205090868730163/1206271989893115
=> Set a time when a specific WTS needs to be updated.

WiserTaskScheduler/WiserTaskScheduler/Core/Services/LogService.cs
Before writing logs to the log file, database and/or Slack all credentials will be checked in the message to be obfuscated.
https://app.asana.com/0/1205090868730163/1206032444292817
=> Obfuscate credentials before writing logs.

WiserTaskScheduler/WiserTaskScheduler/Core/Models/ConfigurationModel.cs, WiserTaskScheduler/WiserTaskScheduler/Modules/DocumentStoreRead/Services/DocumentStoreReadService.cs, WiserTaskScheduler/WiserTaskScheduler/WiserTaskScheduler.csproj
The connection string for the document store can now also be set in the configuration in addition to the normal connection string. This is required when using the document store features.
[Asana ticket](https://app.asana.com/0/1200923549887805/1203802664624132)
=> Set document store connection string

WiserTaskScheduler/WiserTaskScheduler/Modules/ImportFiles/Models/ImportFileModel.cs, WiserTaskScheduler/WiserTaskScheduler/Modules/ImportFiles/Services/ImportFilesService.cs
Added option called `AddSuffixToFileNameAfterProcessing` that will add a suffix to files that are moved to the processed folder. If `ProcessedFolder` is not set, the suffix is not added and nothing happens. The suffix is the date and time in this format: `YYYYMMDDHHMMSS`.
There is no Asana ticket for this PR.
=> Option for suffix for imported files

WiserTaskScheduler/WiserTaskScheduler/Core/Interfaces/ILogService.cs, WiserTaskScheduler/WiserTaskScheduler/Core/Services/LogService.cs, WiserTaskScheduler/WiserTaskScheduler/Modules/HttpApis/Services/HttpApisService.cs
Especially if OAuth tokens are used they can't be set in the credentials for obfuscation. Therefor if API calls include ehaders for "Authorization" or "X-API-Key" the values will be dynamically added for obfuscation in the logs.
https://app.asana.com/0/1205090868730163/1206032444292817
=> Obfuscate authentication headers for API calls

WiserTaskScheduler/WiserTaskScheduler/Modules/Wiser/Services/WiserDashboardService.cs
If a run scheme was completed within a second, for example if it crashed at the beginning, the state would be marked as "success". This happened due to milliseconds not stored in the logs and thus not greater or equal than the start time that did include milliseconds.
https://app.asana.com/0/1205090868730163/1205230396767405
=> Fix WTS service always being marked success

WiserTaskScheduler/WiserTaskScheduler/Modules/Branches/Services/BranchQueueService.cs
Branch creation functionality will now ignore virtual columns.
No specific Asana ticket for this, found this while trying to create a new branch.
=> Ignore virtual columns for branch creation

WiserTaskScheduler/WiserTaskScheduler/Core/Services/ParentUpdateService.cs
the parent update service sometimes crashes, added some try and catches and some logging to give more info
also found a missing {targetDatabase.DatabaseName} somewhere and removed some white spaces
=> adjust parent update service to log more and use try and catch.

WiserTaskScheduler/WiserTaskScheduler/Core/Models/ParentsUpdate/ParentUpdateDatabaseStringsModel.cs, WiserTaskScheduler/WiserTaskScheduler/Core/Models/ParentsUpdate/ParentsUpdateServiceSettings.cs, WiserTaskScheduler/WiserTaskScheduler/Core/Services/ParentUpdateService.cs
Since truncate was not a option we change it to a delete from, but it was requested we also reset the increment and optimize this pr adds these requests.
ran it on wiser demo
- made a an asana task to do this : https://app.asana.com/0/1204371236183532/1207323732304158/f
none
https://app.asana.com/0/1204371236183532/1207266233417805/f
=> add AUTO_INCREMENT reset and OPTIMIZE Table to parent update service

WiserTaskScheduler/WiserTaskScheduler/Core/Services/CleanupService.cs
we have a odd error that keeps crashing the clean up service, the problem is 2 steps, 1 add exception handling and 2 see why we get this error.
this pr is for step 1 though step 2 seems to just be that there are too many records to optimize in 1 go
ran it on demo, but the error does not happen there so difficult to fully test.
none
https://app.asana.com/0/1204371236183532/1207296784409553/f
=> add exception logging to clean up database logic

WiserTaskScheduler/WiserTaskScheduler/Core/Services/LogService.cs, WiserTaskScheduler/WiserTaskScheduler/Core/Workers/MainWorker.cs
Add the name of the server to the Slack messages. Currently if there are mutliple instances of the WTS running and logging to Slack there is no indication which one is giving the errors.
Tested by triggering an error to be send to the Slack channel.
N/A
https://app.asana.com/0/7257459017111/1207193040742584
=> Add server name to messages to Slack

WiserTaskScheduler/WiserTaskScheduler/Core/Services/ConfigurationsService.cs
adding a new skipaction type "onlywithvalue" to check for specific results/targets in a result set
(because now very often we are abusing the the statuscode check for this one.
tested it while working on the slackmessage action
none that are dependent
none
=> add the SkipAction OnlyWithValue

WiserTaskScheduler/WiserTaskScheduler/Modules/Wiser/Services/WiserService.cs
In the appsettings we can set a path/directory from where the WTS needs to load configurations from the templatemodule in Wiser. If the directory that you configured has no templates in it, the function `WiserService.FlattenTree` would crash with a `NullReferenceException`. This PR fixes that, now that function will just return an empty list instead.
By executing the same scenario before and after my change and verify if that fixed the issue.
N/A
No ticket, I noticed this problem while working on something else.
=> Fixed error that occurred when Wiser has no templates

WiserTaskScheduler/WiserTaskScheduler/Core/Helpers/ResultSetHelper.cs
I am working on importing data from an OData API. OData uses dots in some property names. This did not work with the WTS, because the WTS uses dots for JSON paths. So if the JSON has a property `{ "@odata.nextpage": "https://example.com" }`, I couldn't use that in my queries or anything, because the WTS would assume the JSON would look like this: `{ "@odata": { "nextpage": "https://example.com" } }`. I fixed this by checking if the entire key, including dots, exists in the JSON. If so, the value of that key will be returned. If not, the code will work as it did before.
By running the WTS on my dev PC and checking with the debugger if the correct values are retrieved from the JSON.
N/A
CON-258
=> Added support for JSON properties with dots, such as "@odata.nextpage"

WiserTaskScheduler/WiserTaskScheduler/Modules/Branches/Services/BranchQueueService.cs
check and update styledoutput ids inside styled outputs when we encounter a updated id in a merge
tested on wiser demo with local hookup
nein
jira
=> update styledoutput ids when merge is completed in branch service

WiserTaskScheduler/WiserTaskScheduler/Modules/Branches/Services/BranchQueueService.cs
Add the success state to the result set when a branch needs to be merged. It will only be set to `true` when no errors have occured.
Tested by merging a branch and checking if the state is set correctly when the merge was succesfully and when an error occured. Also validated if the value is correctly used for the `OnlyWithSuccessState` check on an action.
N/A
https://app.asana.com/0/7257459017111/1206862111467207
=> Add the success state to the result set for branch merges.

WiserTaskScheduler/WiserTaskScheduler/Modules/Wiser/Services/WiserService.cs
When the refresh token for the Wiser API was invalid/expired it was unable to recover from this. Now it will execute a normal login.
Tested by ensuring an invalid token is sent to the Wiser API to see if it falls back on the normal login.
N/A
https://app.asana.com/0/1205090868730163/1207886429176436
=> Handle if the Wiser refresh token is invalid

WiserTaskScheduler/WiserTaskScheduler/Modules/Wiser/Services/WiserService.cs
When configurations fail to be retrieved from the Wiser API the error message from Wiser will be written to the logs and Slack if connected.
Tested by checking if the flow goes correctly when a normal response is given and an error response.
https://github.com/happy-geeks/wiser/pull/703
https://app.asana.com/0/7257459017111/1207193040742570
=> Show error from Wiser API

WiserTaskScheduler/WiserTaskScheduler/Modules/Wiser/Services/WiserService.cs
The earlier code incorrectly assumed that when the http code was 200 but the result was HTML that meant that wiser was updating.
This bugfix removed this check and instead checks for a 503 Service Unavailable response.
Started the WTS to see if it could get the configurations from Wiser when service is available. 
I did not test the flow for when Wiser is unavailable
N/A
https://app.asana.com/0/7257459017111/1207875524687461/f
=> Log service unavailable from calls to Wiser as information.

WiserTaskScheduler/WiserTaskScheduler/Core/Services/CleanupService.cs
When a configuration is paused (or has a long time between 2 runs) the service would be deleted since the last run could go over the set time. The next run is always updated and is therefor a better indication if the service has been off.
Tested by having a configuration on paused with a last run a couple months old and the next run being updated. This stayed active. When having the next run a couple months old the service was removed from the wts_services table.
N/A
https://app.asana.com/0/7257459017111/1208397668109851
=> Change value for check

WiserTaskScheduler/WiserTaskScheduler/Modules/Branches/Services/BranchQueueService.cs
When a file was deleted from and item all files connected to that item would be removed on production during the merge.
Now it only deletes the specific ID in the database of the removed file. The ID used is passed through the mapping already at this point.
Tested it by uploading an image and deleting the old one. Other scenario's tested were deleting the last image. Having multiple images at once and delete only one. Delete two out of three images. Deleted an image that had another ID on production than on the branch.
N/A
CON-977
=> Fix merge of file deletions

WiserTaskScheduler/WiserTaskScheduler/Modules/Branches/Services/BranchQueueService.cs
When an item was created and deleted before a merge the history entries are being cleaned. The details were left behind because they themselves are not created and deleted but only updated for the item. The check now treats details as the item.
Tested by creating an item, setting details, deleting the item and merge the branch.
N/A
https://app.asana.com/0/1205090868730163/1208660620737639
=> Fix problem that detail history was not cleaned

WiserTaskScheduler/WiserTaskScheduler/Core/Models/WtsSettings.cs, WiserTaskScheduler/WiserTaskScheduler/Core/Services/AutoProjectDeployService.cs, WiserTaskScheduler/WiserTaskScheduler/Core/Services/CleanupService.cs, WiserTaskScheduler/WiserTaskScheduler/Core/Services/ConfigurationsService.cs, WiserTaskScheduler/WiserTaskScheduler/Core/Services/LogService.cs, WiserTaskScheduler/WiserTaskScheduler/Core/Services/MainService.cs, WiserTaskScheduler/WiserTaskScheduler/Core/Services/ParentUpdateService.cs, WiserTaskScheduler/WiserTaskScheduler/Core/Workers/BaseWorker.cs, WiserTaskScheduler/WiserTaskScheduler/Core/Workers/MainWorker.cs
Update usages of machineName with wts name for server identification. This arose from a situation where we had multiple WTS instances writing logs to the same slack channel.
Ran a local script, checked the database wts_logs to see if the wts settings name got logged instead of the machine name. Also ran some logs to slack to see if the machineName got replaced with the wts settings name.
none
https://app.asana.com/0/1207852342873635/1208457193033506
=> Update usages of machineName with wts settings name for better server identification

WiserTaskScheduler/AutoUpdater/AutoUpdater.csproj, WiserTaskScheduler/WiserTaskScheduler/Modules/Branches/Services/BranchQueueService.cs, WiserTaskScheduler/WiserTaskScheduler/WiserTaskScheduler.csproj
When performing a merge the `parent_item_id` in the `wiser_item` tables was copied directly. This change retrieves the mapped value to ensure that the `parent_item_id` is the correct item in the production database.
Tested by having items under a parent and checking during the merge if the correct IDs were found and afterwards in Wiser if they were visible under the correct item in the interface.
N/A
https://app.asana.com/1/5038780173035/project/29553867016121/task/1210856126133150
=> Fix parent item ID not being mapped during merge
